# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='psjjjj',
  syntax='proto2',
  serialized_pb=_b('\n\rrequest.proto\x12\x06psjjjj\"/\n\x0cRequestProto\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x11\n\tvhdl_code\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTPROTO = _descriptor.Descriptor(
  name='RequestProto',
  full_name='psjjjj.RequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='psjjjj.RequestProto.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vhdl_code', full_name='psjjjj.RequestProto.vhdl_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['RequestProto'] = _REQUESTPROTO

RequestProto = _reflection.GeneratedProtocolMessageType('RequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTPROTO,
  __module__ = 'request_pb2'
  # @@protoc_insertion_point(class_scope:psjjjj.RequestProto)
  ))
_sym_db.RegisterMessage(RequestProto)


# @@protoc_insertion_point(module_scope)
